### ISSUE TITLE
Questions about the project.

### ISSUE THREAD

**Issue by Richard5656** [RaidTheWeb/audr32old#1]
Is this a solo project or can I join in?
Is there a documentation for the opcodes?
Can this CPU run an operating system yet?

I was planning to do something similar to this, for a CPU architecture based off of the 6502 but I never finished it.

So, I was wondering if I could contribute to this project :D

Thank you for reading.

**Comment by RaidTheWeb** [comment]
1. It's primarily just my solo hobby project, sorry :sweat_smile: 
2. I mean, kind of. Just in ISA.txt with my notes no proper fleshed out documentation about the function of everything.
3. Not at the moment, but it's certainly capable of something resembling an operating system (I/O, interrupts, etc.) just haven't attempted it because writing stuff in binary with a hex editor is a real pain, so until the assembler works :/

**Comment by Richard5656** [comment]
Thank you for the response. I read through your assembler and it looks like your gonna spend more effort than me writing mine. 😅 I just str toked mine all together rather than going through the effort of writing a whole compiler. 

Good luck with this though.
